# Generated by cucumber-sinatra. (Thu Jun 10 15:28:31 +0100 2010)

require File.join(File.dirname(__FILE__), '..', '..', 'application.rb')

require 'capybara'
require 'capybara/cucumber'
require 'spec'

CASServer.set(:environment, :test)

World do
  Capybara.app = CASServer
  include Capybara
  include Spec::Expectations
  include Spec::Matchers
end
